# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_prioritizr.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_prioritizrDialog(object):
    def setupUi(self, prioritizrDialog):
        prioritizrDialog.setObjectName("prioritizrDialog")
        prioritizrDialog.resize(650, 400)
        prioritizrDialog.setMinimumSize(QtCore.QSize(650, 400))
        self.gridLayout_2 = QtWidgets.QGridLayout(prioritizrDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prioritizrPanelLabel = QtWidgets.QLabel(prioritizrDialog)
        self.prioritizrPanelLabel.setText("")
        self.prioritizrPanelLabel.setPixmap(QtGui.QPixmap(":/logos/images/marxan_logo_panel.png"))
        self.prioritizrPanelLabel.setObjectName("prioritizrPanelLabel")
        self.horizontalLayout_2.addWidget(self.prioritizrPanelLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.boundLineEdit = QtWidgets.QLineEdit(prioritizrDialog)
        self.boundLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.boundLineEdit.setText("")
        self.boundLineEdit.setObjectName("boundLineEdit")
        self.gridLayout.addWidget(self.boundLineEdit, 1, 1, 1, 1)
        self.boundCheckBox = QtWidgets.QCheckBox(prioritizrDialog)
        self.boundCheckBox.setMinimumSize(QtCore.QSize(180, 24))
        self.boundCheckBox.setObjectName("boundCheckBox")
        self.gridLayout.addWidget(self.boundCheckBox, 1, 0, 1, 1)
        self.extraCheckBox = QtWidgets.QCheckBox(prioritizrDialog)
        self.extraCheckBox.setMinimumSize(QtCore.QSize(280, 24))
        self.extraCheckBox.setObjectName("extraCheckBox")
        self.gridLayout.addWidget(self.extraCheckBox, 2, 0, 1, 1)
        self.outputLabel = QtWidgets.QLabel(prioritizrDialog)
        self.outputLabel.setMinimumSize(QtCore.QSize(150, 24))
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout.addWidget(self.outputLabel, 0, 0, 1, 1)
        self.outputLineEdit = QtWidgets.QLineEdit(prioritizrDialog)
        self.outputLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.gridLayout.addWidget(self.outputLineEdit, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem2)
        self.startButton = QtWidgets.QPushButton(prioritizrDialog)
        self.startButton.setMinimumSize(QtCore.QSize(30, 16))
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem3)
        self.closeButton = QtWidgets.QPushButton(prioritizrDialog)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 16))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(prioritizrDialog)
        self.closeButton.clicked.connect(prioritizrDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(prioritizrDialog)

    def retranslateUi(self, prioritizrDialog):
        _translate = QtCore.QCoreApplication.translate
        prioritizrDialog.setWindowTitle(_translate("prioritizrDialog", "Launch Prioritizr"))
        self.boundCheckBox.setText(_translate("prioritizrDialog", "Include boundary cost (BLM)"))
        self.extraCheckBox.setText(_translate("prioritizrDialog", "Produce extra Prioritizr outputs"))
        self.extraCheckBox.setShortcut(_translate("prioritizrDialog", "Ctrl+S"))
        self.outputLabel.setText(_translate("prioritizrDialog", "Output file name"))
        self.startButton.setText(_translate("prioritizrDialog", "Start Prioritizr"))
        self.closeButton.setText(_translate("prioritizrDialog", "Close"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    prioritizrDialog = QtWidgets.QDialog()
    ui = Ui_prioritizrDialog()
    ui.setupUi(prioritizrDialog)
    prioritizrDialog.show()
    sys.exit(app.exec_())
